export const drawSVG = `<svg class="statsSVG" viewBox="0 0 48 48"
   version="1.1"
   id="svg1"
   xml:space="preserve"
   inkscape:export-filename="bitmapa.svg"
   inkscape:export-xdpi="96"
   inkscape:export-ydpi="96"
   xmlns:inkscape="http://www.inkscape.org/namespaces/inkscape"
   xmlns:sodipodi="http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd"
   xmlns="http://www.w3.org/2000/svg"
   xmlns:svg="http://www.w3.org/2000/svg"><sodipodi:namedview
     id="namedview1"
     pagecolor="#505050"
     bordercolor="#ffffff"
     borderopacity="1"
     inkscape:showpageshadow="0"
     inkscape:pageopacity="0"
     inkscape:pagecheckerboard="1"
     inkscape:deskcolor="#505050"
     inkscape:document-units="px" /><defs
     id="defs1" /><g
     inkscape:label="Warstwa 1"
     inkscape:groupmode="layer"
     id="layer1"><g
       inkscape:label="Warstwa 1"
       id="layer1-0"
       transform="translate(-0.17539658,0.26309395)"><circle
         style="fill:#7c7c7c;fill-opacity:1;stroke:#ffffff;stroke-width:3.88784;stroke-miterlimit:5.8;stroke-dasharray:none;stroke-opacity:1;paint-order:stroke fill markers"
         id="path1"
         cx="24.146164"
         cy="23.736906"
         r="20.560524"
         inkscape:label="path1" /></g><rect
       style="fill:#fffbfb;fill-opacity:1;stroke-width:3.90956;stroke-miterlimit:5.8;paint-order:stroke fill markers"
       id="rect2"
       width="34.669914"
       height="5.8465276"
       x="6.6650424"
       y="20.813643" /></g></svg>`